import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1787032378301 implements MigrationInterface {
    name = 'InitialSchema1787032378301'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('info', 'success', 'warning', 'error')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "message" text NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'info', "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."zones_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "zones" ("id" SERIAL NOT NULL, "academic_year_id" integer, "name" character varying(100) NOT NULL, "price" numeric(10,2) NOT NULL, "status" "public"."zones_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_880484a43ca311707b05895bd4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."enrollments_type_enum" AS ENUM('feeding', 'transport')`);
        await queryRunner.query(`CREATE TYPE "public"."enrollments_meal_type_enum" AS ENUM('breakfast', 'lunch', 'both')`);
        await queryRunner.query(`CREATE TYPE "public"."enrollments_status_enum" AS ENUM('active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "enrollments" ("id" SERIAL NOT NULL, "student_id" integer NOT NULL, "type" "public"."enrollments_type_enum" NOT NULL, "meal_type" "public"."enrollments_meal_type_enum", "zone_id" integer, "payment_date" date, "duration_days" integer, "expiry_date" date, "payments" jsonb NOT NULL DEFAULT '{}', "status" "public"."enrollments_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "studentId" integer, "zoneId" integer, CONSTRAINT "PK_7c0f752f9fb68bf6ed7367ab00f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_274da7e1af2462e888c4c16b15" ON "enrollments" ("expiry_date") `);
        await queryRunner.query(`CREATE TYPE "public"."students_status_enum" AS ENUM('active', 'repeating', 'promoted', 'transferred')`);
        await queryRunner.query(`CREATE TABLE "students" ("id" SERIAL NOT NULL, "academic_year_id" integer NOT NULL, "name" character varying(100) NOT NULL, "current_class_id" integer, "former_class" character varying(10), "rank" integer, "marks_percentage" numeric(5,2), "status" "public"."students_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "academicYearId" integer, "currentClassId" integer, CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6bc0f2720400592a016f284ac2" ON "students" ("academic_year_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_77329d8dd9e1d16f58ad7ad0b3" ON "students" ("current_class_id") `);
        await queryRunner.query(`CREATE TABLE "shuffle_results" ("id" SERIAL NOT NULL, "shuffle_session_id" integer NOT NULL, "student_id" integer NOT NULL, "proposed_class_id" integer NOT NULL, "is_manual_override" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "shuffleSessionId" integer, "studentId" integer, "proposedClassId" integer, CONSTRAINT "PK_940452856396d17699559613c6b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shuffle_sessions_algorithm_enum" AS ENUM('round_robin', 'balanced_bands', 'snake_draft', 'auto_promote')`);
        await queryRunner.query(`CREATE TYPE "public"."shuffle_sessions_status_enum" AS ENUM('in_progress', 'pending_approval', 'approved', 'rejected', 'distributed')`);
        await queryRunner.query(`CREATE TABLE "shuffle_sessions" ("id" SERIAL NOT NULL, "academic_year_id" integer NOT NULL, "p_level_id" integer NOT NULL, "algorithm" "public"."shuffle_sessions_algorithm_enum" NOT NULL, "status" "public"."shuffle_sessions_status_enum" NOT NULL DEFAULT 'in_progress', "submitted_by" integer NOT NULL, "reviewed_by" integer, "rejection_note" text, "submitted_at" TIMESTAMP, "reviewed_at" TIMESTAMP, "distributed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "academicYearId" integer, "pLevelId" integer, "submittedByUserId" integer, "reviewedByUserId" integer, CONSTRAINT "PK_c7734fa6eb3b63b50674ff466e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'dean', 'principal', 'teacher', 'accountant')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "email" character varying(150) NOT NULL, "password" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "avatar" text, "must_change_password" boolean NOT NULL DEFAULT true, "failed_login_attempts" integer NOT NULL DEFAULT '0', "locked_until" TIMESTAMP, "last_login" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."classes_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "classes" ("id" SERIAL NOT NULL, "p_level_id" integer NOT NULL, "name" character varying(5) NOT NULL, "teacher_id" integer, "status" "public"."classes_status_enum" NOT NULL DEFAULT 'active', "distributed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "pLevelId" integer, "teacherId" integer, CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82638c162120877aec324e91c3" ON "classes" ("p_level_id") `);
        await queryRunner.query(`CREATE TYPE "public"."p_levels_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "p_levels" ("id" SERIAL NOT NULL, "academic_year_id" integer NOT NULL, "name" character varying(10) NOT NULL, "status" "public"."p_levels_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "academicYearId" integer, CONSTRAINT "PK_954be695a2ec72113a9b18c1fcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32af3cf9b083b25916f2fdfd50" ON "p_levels" ("academic_year_id") `);
        await queryRunner.query(`CREATE TYPE "public"."academic_years_status_enum" AS ENUM('active', 'archived')`);
        await queryRunner.query(`CREATE TYPE "public"."academic_years_deletion_status_enum" AS ENUM('none', 'pending', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "academic_years" ("id" SERIAL NOT NULL, "name" character varying(20) NOT NULL, "status" "public"."academic_years_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "archived_at" TIMESTAMP, "deletion_status" "public"."academic_years_deletion_status_enum" NOT NULL DEFAULT 'none', "deletion_requested_at" TIMESTAMP, CONSTRAINT "PK_2021b90bfbfa6c9da7df34ca1cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_status_enum" AS ENUM('present', 'absent', 'late')`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" SERIAL NOT NULL, "student_id" integer NOT NULL, "class_id" integer NOT NULL, "date" date NOT NULL, "status" "public"."attendance_status_enum" NOT NULL DEFAULT 'present', "marked_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ca727371ba6376f1acdec2a6db7" UNIQUE ("student_id", "date"), CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6200532f3ef99f639a27bdcae7" ON "attendance" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e63ac3a881f4b1ff420942c217" ON "attendance" ("class_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff05fd5159e6d9d99514d46531" ON "attendance" ("date") `);
        await queryRunner.query(`CREATE TABLE "attendance_sessions" ("id" SERIAL NOT NULL, "class_id" integer NOT NULL, "date" date NOT NULL, "marked_by" integer NOT NULL, "present" integer NOT NULL DEFAULT '0', "absent" integer NOT NULL DEFAULT '0', "late" integer NOT NULL DEFAULT '0', "total" integer NOT NULL DEFAULT '0', "submitted_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f2cd9990dd46c63438ee8b52f4e" UNIQUE ("class_id", "date"), CONSTRAINT "PK_84d565d9e484e2bcdaf4a9e1890" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6fc552e07b31ac92445cd3e21f" ON "attendance_sessions" ("class_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_74c8985e5362fc60ec56270433" ON "attendance_sessions" ("date") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "actor_id" integer, "actor_name" character varying NOT NULL DEFAULT 'System', "actor_role" character varying NOT NULL DEFAULT 'system', "action" character varying NOT NULL, "details" text NOT NULL DEFAULT '', "ip_address" character varying NOT NULL DEFAULT '—', CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "timetable_slots" ("id" SERIAL NOT NULL, "plan_id" integer NOT NULL, "p_level_name" character varying(10) NOT NULL, "section_name" character varying(5) NOT NULL, "day" smallint NOT NULL, "period" smallint NOT NULL, "start_time" character varying(5), "end_time" character varying(5), "is_break" boolean NOT NULL DEFAULT false, "course_code" character varying(30), "teacher_name" character varying(100), "is_manual_override" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bbaf53d4b2600b45a0ee6315ecd" UNIQUE ("plan_id", "p_level_name", "section_name", "day", "period"), CONSTRAINT "PK_b2253a56b9d36d00f84aff7efcc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fcb22897c9d1180a062f8cb181" ON "timetable_slots" ("plan_id") `);
        await queryRunner.query(`CREATE TYPE "public"."timetable_plans_status_enum" AS ENUM('draft', 'generated', 'finalized')`);
        await queryRunner.query(`CREATE TABLE "timetable_plans" ("id" SERIAL NOT NULL, "academic_year_id" integer NOT NULL, "name" character varying(100) NOT NULL, "status" "public"."timetable_plans_status_enum" NOT NULL DEFAULT 'draft', "created_by" integer NOT NULL, "skeleton_config" jsonb, "courses_config" jsonb, "teachers_config" jsonb, "generation_log" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b079d38bdd3c16ffaabc1147e84" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_bf3ba3dfa95e2df7388eb4589fd" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_c57785bf900d3c09a35f29edf90" FOREIGN KEY ("zoneId") REFERENCES "zones"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_de076eb45af95b68abe8f199083" FOREIGN KEY ("academicYearId") REFERENCES "academic_years"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_b5a10dd9fbfb4b055173be5c927" FOREIGN KEY ("currentClassId") REFERENCES "classes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shuffle_results" ADD CONSTRAINT "FK_45edebdb2aec4aaed2bd924d96c" FOREIGN KEY ("shuffleSessionId") REFERENCES "shuffle_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shuffle_results" ADD CONSTRAINT "FK_d2510a94f44b592590b66a24fd4" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shuffle_results" ADD CONSTRAINT "FK_470084f9f2f8493c8569f34c7e0" FOREIGN KEY ("proposedClassId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shuffle_sessions" ADD CONSTRAINT "FK_6615a0a959900e3985621e30609" FOREIGN KEY ("academicYearId") REFERENCES "academic_years"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shuffle_sessions" ADD CONSTRAINT "FK_740dd11bea035ecd1481842fad0" FOREIGN KEY ("pLevelId") REFERENCES "p_levels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shuffle_sessions" ADD CONSTRAINT "FK_f1ef5b0ea6f9468ffd1d23990f3" FOREIGN KEY ("submittedByUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shuffle_sessions" ADD CONSTRAINT "FK_a572196a605be04ce86d78cc554" FOREIGN KEY ("reviewedByUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_832189b36c0c99a78554548f8f1" FOREIGN KEY ("pLevelId") REFERENCES "p_levels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_4b7ac7a7eb91f3e04229c7c0b6f" FOREIGN KEY ("teacherId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "p_levels" ADD CONSTRAINT "FK_47952b66581858f2ea52f5db006" FOREIGN KEY ("academicYearId") REFERENCES "academic_years"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" ADD CONSTRAINT "FK_fcb22897c9d1180a062f8cb181b" FOREIGN KEY ("plan_id") REFERENCES "timetable_plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetable_plans" ADD CONSTRAINT "FK_a975ae0f0900faa9d0430e9d1d9" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetable_plans" ADD CONSTRAINT "FK_00b23c8f9163b1c0f728a4b9d65" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "timetable_plans" DROP CONSTRAINT "FK_00b23c8f9163b1c0f728a4b9d65"`);
        await queryRunner.query(`ALTER TABLE "timetable_plans" DROP CONSTRAINT "FK_a975ae0f0900faa9d0430e9d1d9"`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" DROP CONSTRAINT "FK_fcb22897c9d1180a062f8cb181b"`);
        await queryRunner.query(`ALTER TABLE "p_levels" DROP CONSTRAINT "FK_47952b66581858f2ea52f5db006"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_4b7ac7a7eb91f3e04229c7c0b6f"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_832189b36c0c99a78554548f8f1"`);
        await queryRunner.query(`ALTER TABLE "shuffle_sessions" DROP CONSTRAINT "FK_a572196a605be04ce86d78cc554"`);
        await queryRunner.query(`ALTER TABLE "shuffle_sessions" DROP CONSTRAINT "FK_f1ef5b0ea6f9468ffd1d23990f3"`);
        await queryRunner.query(`ALTER TABLE "shuffle_sessions" DROP CONSTRAINT "FK_740dd11bea035ecd1481842fad0"`);
        await queryRunner.query(`ALTER TABLE "shuffle_sessions" DROP CONSTRAINT "FK_6615a0a959900e3985621e30609"`);
        await queryRunner.query(`ALTER TABLE "shuffle_results" DROP CONSTRAINT "FK_470084f9f2f8493c8569f34c7e0"`);
        await queryRunner.query(`ALTER TABLE "shuffle_results" DROP CONSTRAINT "FK_d2510a94f44b592590b66a24fd4"`);
        await queryRunner.query(`ALTER TABLE "shuffle_results" DROP CONSTRAINT "FK_45edebdb2aec4aaed2bd924d96c"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_b5a10dd9fbfb4b055173be5c927"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_de076eb45af95b68abe8f199083"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_c57785bf900d3c09a35f29edf90"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_bf3ba3dfa95e2df7388eb4589fd"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`DROP TABLE "timetable_plans"`);
        await queryRunner.query(`DROP TYPE "public"."timetable_plans_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fcb22897c9d1180a062f8cb181"`);
        await queryRunner.query(`DROP TABLE "timetable_slots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74c8985e5362fc60ec56270433"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6fc552e07b31ac92445cd3e21f"`);
        await queryRunner.query(`DROP TABLE "attendance_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff05fd5159e6d9d99514d46531"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e63ac3a881f4b1ff420942c217"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6200532f3ef99f639a27bdcae7"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_status_enum"`);
        await queryRunner.query(`DROP TABLE "academic_years"`);
        await queryRunner.query(`DROP TYPE "public"."academic_years_deletion_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."academic_years_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32af3cf9b083b25916f2fdfd50"`);
        await queryRunner.query(`DROP TABLE "p_levels"`);
        await queryRunner.query(`DROP TYPE "public"."p_levels_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82638c162120877aec324e91c3"`);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP TYPE "public"."classes_status_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "shuffle_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."shuffle_sessions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."shuffle_sessions_algorithm_enum"`);
        await queryRunner.query(`DROP TABLE "shuffle_results"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77329d8dd9e1d16f58ad7ad0b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bc0f2720400592a016f284ac2"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TYPE "public"."students_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_274da7e1af2462e888c4c16b15"`);
        await queryRunner.query(`DROP TABLE "enrollments"`);
        await queryRunner.query(`DROP TYPE "public"."enrollments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."enrollments_meal_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."enrollments_type_enum"`);
        await queryRunner.query(`DROP TABLE "zones"`);
        await queryRunner.query(`DROP TYPE "public"."zones_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
    }

}
